
version: '3.7'

services:
  dynamodb-local-admin-gui:
    container_name: dynamodb-local-admin-gui
    image: instructure/dynamo-local-admin
    ports:
      - '8000:8000'
    volumes:
      - db-volume:/var/lib/dynamodb/
      

volumes:
  db-volume:
