package com.example.booksRenting.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import org.springframework.data.annotation.Id;


@DynamoDBTable(tableName = "books")
public abstract class BaseEntity {

    @Data
    public static class BaseEntityId {
        @DynamoDBHashKey(attributeName = "pk")
        @DynamoDBAutoGeneratedKey
        private String pk;

        @DynamoDBRangeKey(attributeName = "sk")
        private String sk;
    }

    @Id
    private BaseEntityId id = new BaseEntityId();

    @DynamoDBHashKey(attributeName = "pk")
    @DynamoDBAutoGeneratedKey
    public String getPk() {
        return id.getPk();
    }
    public void setPk(String pk) {
        id.setPk(pk);
    }

    public String getSk() {
        return id.getSk();
    }
    public void setSk(String sk) {
        id.setSk(sk);
    }

}
