package com.example.booksRenting.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "books") //TODO Dynamiczna nazwa tabeli
public abstract class BaseEntity {

    @Data
    public static class BaseEntityId {
        @DynamoDBHashKey(attributeName = "pk")
        @DynamoDBAutoGeneratedKey
        private String pk;

        @DynamoDBRangeKey(attributeName = "sk")
        private String sk;
    }

    @Id
    private BaseEntityId id = new BaseEntityId();

    @DynamoDBHashKey(attributeName = "pk")
    @DynamoDBAutoGeneratedKey
    public String getPk() {
        return id.getPk();
    }
    public void setPk(String pk) {
        id.setPk(pk);
    }

    @DynamoDBRangeKey(attributeName = "sk")
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "userId")
    public String getSk() {
        return id.getSk();
    }
    public void setSk(String sk) {
        id.setSk(sk);
    }

}
