package com.example.booksRenting.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "books") //TODO Dynamiczna nazwa tabeli
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Book {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    String id;

    @DynamoDBAttribute
    String title;

    @DynamoDBAttribute
    String author;
}
