reservation:
  duration: P7D

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_rFViaC5CP
com:
  example:
    security:
      jwt:
        aws:
          userPoolId: eu-central-1_rFViaC5CP
          region: "eu-central-1"
