aws:
  dynamodb:
    endpoint: http://localhost:8000/
  accessKeyId: key
  secretKey:
  region: us-east-1

reservation:
  duration: PT20S

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_fcpozvXGB

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_fcpozvXGB/.well-known/jwks.json

com:
  example:
    security:
      jwt:
        aws:
          userPoolId: us-east-1_fcpozvXGB
          region: "us-east-1"
