aws:
  dynamodb:
    endpoint: http://localhost:8000/
  accessKeyId: key
  secretKey:
  region: us-east-1

reservation:
  duration: PT20S

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_rFViaC5CP

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_rFViaC5CP/.well-known/jwks.json

com:
  example:
    security:
      jwt:
        aws:
          userPoolId: eu-central-1_rFViaC5CP
          region: "eu-central-1"
