aws:
  dynamodb:
    endpoint: http://localhost:8000/
  accessKeyId: key
  secretKey:
  region: us-east-1

reservation:
  duration: PT20S

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 1piu2njoj8f14iu5m64b8pmk7m
            clientSecret: 1tbd7hm4k1qsva87mbqvkpme6b1coq54okmrfuus76t6t21ckh5v
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            clientName: Books Renting
            authorization-grant-type: authorization_code
        provider:
          cognito:
            authorizationUri: https://niezly-books-renting.auth.us-east-1.amazoncognito.com/oauth2/authorize
            tokenUri: https://niezly-books-renting.auth.us-east-1.amazoncognito.com/oauth2/token
            jwkSetUri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_fcpozvXGB/.well-known/jwks.json
            nick-name-attribute: username
